[build]
  publish = "site"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/dashboardApi/:splat"
  status = 200

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/dashboardAuth"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/home.html"
  status = 200