[build]
  publish = "src/dashboard/public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/:splat"
  status = 200