[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev:dashboard"
  port = 3000
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/dashboard/auth/:splat"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/.netlify/functions/dashboard/dashboard/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["express", "express-session", "passport", "passport-discord", "express-ejs-layouts"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
