[build]
  # command = "npm run build" (Keep this removed)
  # publish = "dist"         (Keep this removed)
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/templates/**"]