name: Node.js CI

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop
    workflow_dispatch: # Allow manual triggering

jobs:
    build-and-test:
        name: Build & Test (Node ${{ matrix.node-version }})
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]
            fail-fast: false

        env:
            NODE_ENV: test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1 # Fetch only the latest commit for better performance

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint
              continue-on-error: false

            - name: Apply code formatting
              run: npm run format

    security-scan:
        name: Security Scan
        runs-on: ubuntu-latest
        needs: build-and-test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: npm ci

            - name: Run npm audit
              run: npm audit --production
              continue-on-error: true

    deploy-docs:
        name: Deploy Documentation
        runs-on: ubuntu-latest
        needs: build-and-test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: npm ci

            - name: Build documentation
              run: |
                  if [ -f "package.json" ] && grep -q "docs:build" "package.json"; then
                    npm run docs:build
                  elif [ -d "docs" ]; then
                    echo "Documentation directory exists but no build script found"
                  else
                    echo "No documentation to build"
                    exit 0
                  fi

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: docs
                  branch: gh-pages
                  clean: true
