name: CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    lint:
        name: Lint Code
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run Prettier write
              run: npx prettier --write .

    test:
        name: Run Tests
        runs-on: ubuntu-latest
        needs: lint
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Create .env file
              run: |
                  touch .env
                  echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_TEST }}" >> .env
                  echo "CLIENTID=${{ secrets.CLIENTID_TEST }}" >> .env
                  echo "MONGODB_URL=${{ secrets.MONGODB_URL_TEST }}" >> .env
                  echo "LOG_LEVEL=INFO" >> .env
                  echo "LOG_TO_FILE=false" >> .env

            - name: Run tests
              run: npm test
              env:
                  NODE_ENV: test
